version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/myfrontend/Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
